from. about import about
from .admin_amend import admin_amend
from .admin_create import admin_create
from .admin_dashboard import admin_dashboard
from .admin_delete import admin_delete
from .admin_login import admin_login
from .contact import contact
from .discog_entry import discog_entry
from .discography import discography
from .home_page import home_page
from .production_page import production_page
